- hosts: all
  become: yes
  tasks:
  - name: setup purging of old kernels
    package:
      name: byobu
      state: latest
- hosts: all
  become: yes
  serial: 1
  tasks:
  - include_role:
      name: docker
- hosts: logservers
  become: yes
  tasks:
  - include_role:
      name: firewalled
  - include_role:
      name: telemetry
- hosts: swarms
  become: yes
  serial: 1
  tasks:
  - include_role:
      name: swarm
- hosts: all
  become: yes
  tasks:
  - include_role:
      name: telegraf
- hosts: gluster
  become: yes
  tasks:
  - include_role:
      name: gluster
