- hosts: logservers
  become: yes
  tasks:
  - include_role:
      name: telemetry
- hosts: swarms
  become: yes
  serial: 1
  tasks:
  - include_role:
      name: swarm
- hosts: all
  become: yes
  tasks:
  - include_role:
      name: telegraf