version: '3.1'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    volumes:
      - mongo_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 128m
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 1g
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: itzg/graylog:swarm-transport-ip
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 756m
    env_file:
      - graylog.env
    environment:
      GRAYLOG_SERVER_JAVA_OPTS: -Xmx512m
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # plaintext
      - 5555:5555
  influxdb:
    image: influxdb:1.4.2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: metrics
    volumes:
      - influxdb_data:/var/lib/influxdb
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 756m
  chronograf:
    # NOTE: internally binds to 8888
    image: chronograf:1.3.10
    command: --influxdb-url=http://influxdb:8086
    env_file:
      - influx.env
    volumes:
      - chronograf_data:/var/lib/chronograf
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 128m
#  grafana:
#    image: grafana/grafana:4.6.2
#    env_file:
#      - grafana.env
#    environment:
#      GF_INSTALL_PLUGINS: raintank-worldping-app
#    volumes:
#      - grafana_data:/var/lib/grafana
#    deploy:
#      placement:
#        constraints:
#          - node.labels.storage == 1
  haproxy:
    image: itzg/haproxy-lets
    env_file:
      - haproxy.env
    volumes:
      - haproxy_certs:/certs
      - haproxy_config:/config
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.storage == 1
      resources:
        limits:
          memory: 128m

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
  es_data:
  graylog_journal:
  haproxy_certs:
  haproxy_config:
  influxdb_data:
  chronograf_data:
  grafana_data:
