- name: install apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
- name: add apt source
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ansible_distribution_release}} stable"
- name: install telegraf
  package:
    name: telegraf
- name: install configs
  template:
    src: "{{item}}.j2"
    dest: "/etc/telegraf/telegraf.d/{{item}}.conf"
  with_items:
    - out_influxdb
    - in_docker
  register: configs_result
- name: remove configs
  file:
    path: "/etc/telegraf/telegraf.d/{{item}}.conf"
    state: absent
  with_items:
    - out_graylog
  register: configs_rm_result
- name: enable telegraf access to docker
  user:
    name: telegraf
    append: yes
    groups: docker
- name: restart service
  when: configs_result.changed or configs_rm_result.changed
  service:
    name: telegraf
    state: restarted